# AU Rules to fetch various GEO Data

[fetcher_matcher]
catalog = "locality/boundary"
rest_url = "https://data.gov.au/api/v0/search/datasets"
query = "locality boundaries"
matcher = '^https://data.gov.au/data(?:(/dataset|set))/[a-f0-9\-]+/resource/[a-f0-9\-]+/download/[A-Za-z0-9_]+(?:([_\-]?gda[0-9]*|)).zip$'

